main.tf
In the example code, we leave the `ami_id` param blank by default and fetch our public images to make it easier to get started. In one place, we forgot to swap in the public image, so we were trying to use a blank `ami_id` value.
=> Fix bug with AMI ID

main.tf, variables.tf
Currently the instance type is not configurable from the 'top-level' module. So when instantiating they default to the standard t2.micro. Since they have very little memory, they are not really feasible for the job.
=> Configurable instance type

examples/nomad-consul-ami/nomad-consul-docker.json, examples/nomad-consul-ami/nomad-consul.json, examples/nomad-consul-separate-cluster/main.tf, main.tf
Upgrade versions of nomad and consul used in the repository and in the examples.
**Version Upgrade:**
- nomad: 0.6.3 -> 0.7.1
- consul: 0.9.3 -> 1.0.3
- consul terraform module: 0.0.3 -> 0.1.0
**Tests:**
- Running packer build for `nomad-consul-docker` ( Amazon Linux and Ubuntu )
- `nomad-consul` without Docker support can be considered a subset.
- Running test deployment of `examples/nomad-consul-separate-cluster`
- Checked connection of consul server and agents
- Checked nomad status after terraform deployment
- Checked deployment and functionality of the cluster with an example service job, not just the default batch job.
=> Everything kept working as it did before.
=> Feature/upgrade versions Nomad, Consul

modules/nomad-cluster/README.md, modules/nomad-cluster/main.tf, modules/nomad-cluster/variables.tf
Fixes #19
This is backwards incompatible and a breaking change.
For each existing load balancer specified with the `load_balancers` variable, define a new `aws_autoscaling_attachment` . For example:
```hcl
resource "aws_elb" "bar" {
// ...
}
module "nomad" {
source ="..."
// ...
}
resource "aws_autoscaling_attachment" "asg_attachment_bar" {
autoscaling_group_name = "${module.nomad.asg_name}"
elb                    = "${aws_elb.bar.id}"
}
```
For each existing target group specified with the `target_group_arns` variable, define a new `aws_autoscaling_attachment` . For example:
```hcl
resource "aws_lb_target_group" "test" {
// ...
}
module "nomad" {
source ="..."
// ...
}
resource "aws_autoscaling_attachment" "asg_attachment_bar" {
autoscaling_group_name = "${module.nomad.asg_name}" …
```
=> Use `aws_autoscaling_attachment` instead

examples/nomad-consul-separate-cluster/main.tf
using non ssh version of github.com reference to work for those of us that dont have a ssh key to the consul repo.  :-)
=> examples - changed to different repo format

examples/nomad-consul-ami/nomad-consul-docker.json, examples/nomad-consul-ami/nomad-consul.json, examples/nomad-consul-separate-cluster/main.tf, main.tf, modules/nomad-cluster/outputs.tf, modules/nomad-security-group-rules/README.md, test/glide.yaml
Fix a bunch of minor bugs that have crept up due to CI issues with running tests:
1. Update Consul usage to v0.3.1 everywhere, so the `tags` param is exposed. This fixes #26.
1. Update all Git URLs to use HTTPS instead of SSH for consistency.
1. Fix tags set on Nomad cluster in root example. Nomad clients should not get the same tags as servers.
=> Fix Consul version. Fix Git URLs. Fix Nomad tags.

examples/nomad-consul-separate-cluster/README.md, examples/nomad-consul-separate-cluster/main.tf, examples/nomad-consul-separate-cluster/outputs.tf, examples/nomad-consul-separate-cluster/variables.tf, examples/root-example/README.md, main.tf, outputs.tf, test/Gopkg.lock, test/Gopkg.toml, test/nomad_helpers.go, variables.tf
I’m removing the `provider` block and `aws_region` variable from the examples in this repo so that they work properly with the instructions you get from the auto-generated docs on the [Terraform Registry page](https://registry.terraform.io/modules/hashicorp/nomad/aws/0.4.0) for this module.
=> Remove provider and aws_region from examples

modules/run-nomad/run-nomad
Use case includes adding `VAULT_TOKEN` for integration with Vault.
All the test pass.
[test.log](https://github.com/hashicorp/terraform-aws-nomad/files/2052275/test.log)
=> Add environment variables to supervisor configuration

examples/nomad-consul-separate-cluster/main.tf, modules/nomad-cluster/main.tf, modules/nomad-cluster/variables.tf
The current solution does not support to attach ebs_volumes to the nomad nodes.
NEW: With this change it is possible to inject ebs_block_device configuration into the launch configuration for the nomad nodes.
TEST: Tested with running/ self-contained examples setting up a nomad-cluster w. multiple dc's (see: https://github.com/MatthiasScholz/cos/tree/master/examples/root-example and https://github.com/MatthiasScholz/cos/tree/master/examples/nomad-datacenter)
=> Add possibility to add ebs_volumes for nomad nodes

README.md
We've had a lot of confusion about the purpose of the code in the root of this repo. This is an attempt to improve the docs to make this more clear. Feedback welcome on how to make it even clearer.
See also https://github.com/hashicorp/terraform-aws-vault/pull/137 and https://github.com/hashicorp/terraform-aws-consul/pull/118.
=> Update docs to clarify role of root of repo

.circleci/config.yml, examples/nomad-consul-separate-cluster/main.tf, examples/nomad-consul-separate-cluster/outputs.tf, examples/nomad-consul-separate-cluster/variables.tf, main.tf, modules/nomad-cluster/README.md, modules/nomad-cluster/main.tf, modules/nomad-cluster/outputs.tf, modules/nomad-cluster/variables.tf, modules/nomad-security-group-rules/README.md, modules/nomad-security-group-rules/main.tf, modules/nomad-security-group-rules/variables.tf, outputs.tf, test/Gopkg.lock, test/Gopkg.toml, test/nomad_helpers.go, variables.tf
This PR makes all modules and examples compatible with Terraform 0.12.x. Also upgraded tests to use terratest version to 0.17.4
Please note that this change is BACKWARDS INCOMPATIBLE and you MUST use Terraform 0.12.x and above with the code once this has been merged.
=> Terraform 0.12.x Upgrade

modules/nomad-security-group-rules/main.tf
Issue https://github.com/hashicorp/terraform-aws-nomad/issues/59
The error is caused by trying to create a SG rule with 0 CIDRs.
Error produced in terraform:
```
Error: One of ['cidr_blocks', 'ipv6_cidr_blocks', 'self', 'source_security_group_id', 'prefix_list_ids'] must be set to create an AWS Security Group Rule
```
This pull request brings the nomad module inline with how the Vault and Consul modules handle this. The addition of toggling count when there are no CIDRs will prevent the SG rules from being created and causing an error. There should be no backwards compatibility issues or downtime.
=> [nomad-security-group-rules] allow empty list of allowed inbound CIDRs

examples/nomad-consul-ami/nomad-consul.json
Changed clean_ami_name to clean_resource_name.
clean_ami_name was deprecated in 1.5.0: https://github.com/hashicorp/packer/blob/master/CHANGELOG.md#backwards-incompatibilities-1
=> Packer 1.5+ support

examples/nomad-consul-ami/setup_amazon-linux-2.sh
After #62, Docker no longer starts on startup when creating an instance from the example AMI, thus Nomad isn't able to use Docker as a driver.
=> Enable Docker in Amazon Linux 2 AMI example

modules/nomad-cluster/main.tf
If the volume_size is 0 then we assume that a snapshotid is available and use that one instead.
AWS requires either a volume size or a snapshotid.
It seems that Terraform filters a volume size of 0 out of the request to AWS.
https://github.com/hashicorp/terraform-aws-nomad/issues/63
=> Fix missing snapshot id in ebs devices in nomad cluster

modules/nomad-cluster/main.tf, modules/nomad-cluster/variables.tf
This change solve issue: https://github.com/hashicorp/terraform-aws-nomad/issues/70
The changes are tested with an existing nomad-cluster without scale-in protection. The optional scale-in protection is set to true.
The terraform plan output is here:
https://gist.github.com/mawa-jnd/1f1ee3c744f9c38718527c240a5d9475
The change is:
- backward compatible
- has no downtime with default setup as changing the ASG will not automatically restart instances
=> Add instance scale-in protection for nomad-cluster

examples/nomad-consul-ami/nomad-consul-docker.json, examples/nomad-consul-ami/nomad-consul.json, examples/nomad-consul-separate-cluster/main.tf, main.tf, modules/nomad-cluster/variables.tf, modules/nomad-security-group-rules/README.md, test/nomad_helpers.go, test/terratest_helpers.go
AWS Provider 3.0.0 just came out and has a bunch of backwards incompatible changes. This updates this repo to work with 3.x.
=> AWS Provider 3.x and other fixes

modules/nomad-cluster/main.tf, modules/nomad-cluster/variables.tf
Provides flexibility to users for setting `permissions_boundary` to the created IAM role.
Defaults to `null` to preserve the same behavior as before.
=> Add `permissions_boundary` for created IAM role.

examples/nomad-examples-helper/nomad-examples-helper.sh
This fixes `get_nomad_server_ips` not being able to run
=> Fix nomad-examples-helper.sh

.circleci/config.yml, examples/nomad-consul-ami/nomad-consul-docker.json, examples/nomad-consul-ami/nomad-consul.json, main.tf, modules/install-nomad/install-nomad, test/nomad_cluster_ssh_test.go, test/nomad_consul_cluster_colocated_test.go, test/nomad_consul_cluster_separate_test.go, variables.tf
Addresses feature request #80 and fixes issue #90 in the process. First time contribution so I could use help figuring out how to test this.
* Split the amazon-linux-2-ami AMI into amazon-linux-2-amd64-ami and amazon-linux-2-arm64-ami
* Build ARM64 AMIs for Amazon Linux 2 for both docker + without docker
* Set server instance_type to a variable server_instance_type to allow for ARM64 support
* Nomad 0.9.1 -> 1.1.1
* Consul 1.5.1 -> 1.9.6
* Fix clean_ami_name deprecation with clean_resource_name
=> ARM64 support + Version bumps
